POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imlua2ludmlzc2libGUiLCJpZCI6IjY3NWM4MGM5Yjg1OWFiNTA2ZTI3NzM5NCIsImlhdCI6MTczNDExNzE5NywiZXhwIjoxNzM0MTI0Mzk3fQ.0qIiWp_VwV9byjvzLY5jdgJzAxtazT-tCrg7A4RPCq4

{
    "title": "RESTful Backend development",
    "author": "Inkinvissible",
    "url": "https://google.com",
    "likes": 5
}