POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "La importancia del console.log() en Web Development",
    "author": "Anna Gety",
    "url": "https://google.com",
    "likes": 5
}