POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imlua2ludmlzc2libGUiLCJpZCI6IjY3NWM4MGM5Yjg1OWFiNTA2ZTI3NzM5NCIsImlhdCI6MTczNDEyOTg2OSwiZXhwIjoxNzM0MTM3MDY5fQ.sZ207PZwMpknOyTtsKVzVpDx6PUPk6kRj9BOGzwBc88

{
    "title": "React y Node.js para el Backend development",
    "author": "Inkinvissible",
    "url": "https://google.com",
    "likes": 5
}